# Getting ready to test. When pull into staging version: minor
permissions:
  contents: write

name: Minor version on PR merge from dev to staging

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  bump-minor-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Bump minor version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npm version minor
          git push origin staging --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
